-- PTO Time Off Log → pto_ledger (does NOT change balances)
-- Idempotent: removes prior Sheet log import rows first
DELETE FROM pto_ledger WHERE source = 'import' AND note LIKE 'Sheet log%';
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2025-10-15', 'sick', 8, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (4, '2025-10-15', 'vacation', 40, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (4, '2025-10-15', 'sick', 13, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (6, '2025-10-15', 'vacation', 120, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (6, '2025-10-15', 'sick', 48, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (21, '2025-10-15', 'vacation', 16, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (21, '2025-10-15', 'sick', 38, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (28, '2025-10-15', 'vacation', 32, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (28, '2025-10-15', 'sick', 5, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (15, '2025-10-15', 'vacation', 8, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (15, '2025-10-15', 'sick', 8, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (23, '2025-10-15', 'vacation', 80, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (23, '2025-10-15', 'sick', 40, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2025-10-15', 'vacation', 64, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2025-10-15', 'sick', 20, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (1, '2025-10-15', 'vacation', 80, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (1, '2025-10-15', 'sick', 40, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (11, '2025-10-15', 'sick', 10, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (25, '2025-10-15', 'vacation', 40, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (25, '2025-10-15', 'sick', 40, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (7, '2025-10-15', 'vacation', 48, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (7, '2025-10-15', 'sick', 24, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2025-10-15', 'vacation', 2, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2025-10-15', 'sick', 40, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (13, '2025-10-15', 'vacation', 16, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (13, '2025-10-15', 'sick', 30, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (8, '2025-10-15', 'vacation', 40, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (8, '2025-10-15', 'sick', 48, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (2, '2025-10-15', 'sick', 31, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (14, '2025-10-15', 'sick', 37, 'import', 'Sheet log · Migration to new list · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (20, '2025-10-17', 'sick', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (2, '2025-10-17', 'sick', 7, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2025-10-17', 'sick', 2, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (9, '2025-10-17', 'sick', 10, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (11, '2025-10-17', 'sick', 16, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2025-10-21', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (7, '2025-10-21', 'sick', 7, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (28, '2025-10-24', 'vacation', 10, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (15, '2021-10-24', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (20, '2025-10-24', 'sick', 23, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (13, '2025-10-24', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (11, '2025-10-24', 'sick', 2, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (7, '2025-10-24', 'sick', 7, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (23, '2025-10-28', 'vacation', 80, 'import', 'Sheet log · Reimbursement for Maternity Leave · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (23, '2025-10-28', 'sick', 40, 'import', 'Sheet log · Reimbursement for Maternity Leave · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2025-10-28', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2025-10-28', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (20, '2025-10-28', 'sick', 5, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (4, '2025-10-28', 'sick', 5, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (2, '2025-10-28', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (2, '2025-10-28', 'sick', 2, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2025-11-03', 'vacation', 20, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (4, '2025-11-03', 'vacation', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (14, '2025-11-03', 'vacation', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (13, '2025-11-03', 'vacation', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2025-11-05', 'sick', 1, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (8, '2025-11-10', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (15, '2025-11-10', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (13, '2025-11-10', 'vacation', 18, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (13, '2025-11-10', 'sick', 2, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2025-11-10', 'vacation', 3, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2025-11-10', 'sick', 21, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (7, '2025-11-10', 'vacation', 12, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (7, '2025-11-10', 'sick', 2, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2025-11-10', 'sick', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (9, '2025-11-10', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (14, '2025-11-10', 'vacation', 4, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (14, '2025-11-10', 'sick', 3, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (20, '2025-11-10', 'sick', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (4, '2025-11-10', 'vacation', 16, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2025-11-11', 'sick', 2, 'import', 'Sheet log · underpaid 2hrs so Eric gave him cash · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2025-11-17', 'vacation', 11, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (7, '2025-11-17', 'vacation', 3, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (15, '2025-11-17', 'vacation', 7, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2025-11-17', 'vacation', 2, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (11, '2025-11-17', 'sick', 12, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2025-11-17', 'vacation', 2, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2025-11-17', 'sick', 4, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (9, '2025-11-17', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (4, '2025-11-18', 'sick', 3, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (2, '2025-11-24', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (28, '2025-11-24', 'sick', 4, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (20, '2025-11-24', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (7, '2025-11-24', 'vacation', 1, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2025-11-24', 'vacation', 3, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2025-12-01', 'vacation', 5, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (11, '2025-12-01', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (7, '2025-12-01', 'vacation', 16, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (21, '2025-12-01', 'vacation', 10, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (21, '2025-12-01', 'sick', 2, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (28, '2025-12-01', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (14, '2025-12-01', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (15, '2025-12-01', 'sick', 11, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2025-12-01', 'vacation', 12, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2025-12-01', 'vacation', 15, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (2, '2025-12-04', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (15, '2025-12-09', 'sick', 2, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (28, '2025-12-09', 'sick', 7, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (9, '2025-12-09', 'sick', 3, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (11, '2025-12-16', 'vacation', 5, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2025-12-16', 'vacation', 3, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (21, '2025-12-16', 'vacation', 16, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (15, '2025-12-16', 'vacation', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (15, '2025-12-16', 'sick', 19, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2025-12-16', 'vacation', 2, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (9, '2025-12-16', 'sick', 5, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (14, '2025-12-16', 'vacation', 16, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2025-12-12', 'vacation', 12, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (8, '2025-12-15', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (8, '2025-12-16', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2025-12-22', 'vacation', 1, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (28, '2025-12-22', 'sick', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2025-12-29', 'vacation', 7, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (11, '2025-12-29', 'vacation', 24, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (20, '2025-12-29', 'vacation', 9, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (28, '2025-12-29', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (15, '2025-12-29', 'vacation', 17, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (22, '2025-12-29', 'vacation', 11, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2025-12-29', 'vacation', 10, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2025-12-29', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (14, '2025-12-29', 'vacation', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (22, '2026-01-06', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2026-01-06', 'vacation', 10, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (2, '2026-01-06', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (28, '2026-01-06', 'vacation', 32, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (15, '2026-01-06', 'vacation', 12, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2026-01-06', 'vacation', 4, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (9, '2026-01-06', 'sick', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (11, '2026-01-13', 'vacation', 3, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2026-01-13', 'vacation', 1, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (28, '2026-01-13', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (28, '2026-01-13', 'sick', 5, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (15, '2026-01-13', 'vacation', 7, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2026-01-13', 'sick', 7, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (9, '2026-01-13', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (8, '2026-01-13', 'sick', 4, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (13, '2026-01-13', 'sick', 2, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (4, '2026-01-20', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (20, '2026-01-20', 'vacation', 7, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (28, '2026-01-20', 'sick', 4, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (15, '2026-01-20', 'vacation', 13, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2026-01-20', 'vacation', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (13, '2026-01-20', 'sick', 3, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2026-01-26', 'vacation', 32, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (3, '2026-01-26', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (15, '2026-01-26', 'vacation', 3, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2026-01-26', 'vacation', 20, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (28, '2026-01-26', 'vacation', 4, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (28, '2026-01-26', 'sick', 1, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (13, '2026-01-26', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (9, '2026-01-16', 'vacation', 19, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2026-02-04', 'vacation', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (11, '2026-02-04', 'sick', 4, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2026-02-04', 'sick', 5, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (21, '2026-02-04', 'vacation', 16, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (28, '2026-02-04', 'vacation', 16, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (15, '2026-02-04', 'vacation', 29, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (13, '2026-02-04', 'sick', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (4, '2026-02-04', 'vacation', 16, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (9, '2026-02-04', 'vacation', 13, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (3, '2026-02-09', 'sick', 1, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2026-02-09', 'vacation', 16, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2026-02-09', 'sick', 11, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (21, '2026-02-09', 'vacation', 5, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (20, '2026-02-09', 'vacation', 3, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (28, '2026-02-09', 'vacation', 10, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (4, '2026-02-09', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (8, '2026-02-09', 'sick', 28, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (15, '2026-02-09', 'vacation', 10, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (21, '2026-02-16', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (20, '2026-02-16', 'vacation', 7, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (13, '2026-02-16', 'sick', 11, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2026-02-16', 'vacation', 14, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (8, '2026-02-16', 'vacation', 26, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2026-02-16', 'sick', 3, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2026-02-23', 'vacation', 4, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (3, '2026-02-23', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2026-02-23', 'sick', 1, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (22, '2026-02-24', 'sick', 1, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (22, '2026-03-02', 'sick', 2, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2026-03-04', 'sick', 4, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (3, '2026-03-04', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2026-03-16', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (22, '2026-03-16', 'sick', 4, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2026-03-16', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (8, '2026-03-20', 'vacation', 13, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2026-03-20', 'vacation', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (21, '2026-03-20', 'vacation', 9, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (13, '2026-03-20', 'vacation', 2, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2026-03-20', 'sick', 14, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (20, '2026-03-23', 'vacation', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (8, '2026-03-23', 'vacation', 12, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (13, '2026-03-23', 'sick', 10, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2026-04-03', 'sick', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (8, '2026-04-03', 'vacation', 5, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (14, '2026-04-03', 'sick', 16, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2026-04-10', 'vacation', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2026-04-10', 'vacation', 10, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2026-04-10', 'sick', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (21, '2026-04-10', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (14, '2026-04-10', 'sick', 16, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2026-04-10', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (8, '2026-04-10', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (30, '2026-04-10', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2026-04-17', 'vacation', 5, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (18, '2026-04-17', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (3, '2026-04-17', 'sick', 9, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (21, '2026-04-24', 'vacation', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (1, '2026-05-08', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (30, '2026-05-08', 'sick', 16, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2026-05-15', 'sick', 2, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (14, '2026-05-23', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (30, '2026-05-23', 'sick', 16, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (13, '2026-05-23', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (21, '2026-05-23', 'vacation', 2, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2026-05-26', 'vacation', 7, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (22, '2026-05-26', 'sick', 4, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2026-05-26', 'sick', 9, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2026-06-05', 'sick', 3, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (22, '2026-06-05', 'sick', 4, 'import', 'Sheet log · Chris · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (23, '2026-06-05', 'sick', 31, 'import', 'Sheet log · Bianca Sick Pay Advancement · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2026-06-12', 'vacation', 3, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2026-06-12', 'sick', 4, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (22, '2026-06-12', 'sick', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (21, '2026-06-12', 'vacation', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (3, '2026-06-12', 'vacation', 32, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (3, '2026-06-12', 'sick', 14, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (30, '2025-06-19', 'vacation', 25, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2026-06-27', 'vacation', 7, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2026-06-27', 'vacation', 5, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (30, '2026-06-27', 'vacation', 22, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (7, '2026-06-25', 'vacation', 16, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (2, '2026-07-14', 'vacation', 16, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (25, '2026-07-24', 'sick', 6, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (21, '2026-07-24', 'sick', 11, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (7, '2026-07-24', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (25, '2026-07-31', 'sick', 12, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (18, '2026-07-31', 'vacation', 25, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (13, '2026-07-31', 'vacation', 2, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (5, '2026-07-31', 'vacation', 9, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (7, '2026-07-31', 'sick', 2, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (12, '2026-08-07', 'vacation', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (31, '2026-08-07', 'sick', 2, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (10, '2026-08-14', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (31, '2026-08-14', 'sick', 5, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (7, '2026-08-14', 'sick', 8, 'import', 'Sheet log · per employee request · by Chris Marroquin');
INSERT INTO pto_ledger (employee_id, entry_date, kind, hours, source, note) VALUES (15, '2026-08-21', 'sick', 7, 'import', 'Sheet log · per employee request · by Chris Marroquin');
