/**
 * Snapshot from Google Sheet "Total Assurance PTO Tracker" Employees tab
 * (imported into Field App — sheet remains backup).
 */
export type PtoImportRow = {
  name: string;
  hire_date?: string;
  birthday?: string;
  vacation_entitlement?: number;
  vacation_used?: number;
  sick_entitlement?: number;
  sick_used?: number;
};

/** Current Employees sheet values (hours). Update when re-importing. */
export const PTO_SHEET_EMPLOYEES: PtoImportRow[] = [
  { name: "Abelardo Herrera", hire_date: "07/29/2024", birthday: "12/28", vacation_entitlement: 40, vacation_used: 0, sick_entitlement: 40, sick_used: 0 },
  { name: "Adam M Bosquez", hire_date: "11/23/2015", birthday: "06/25", vacation_entitlement: 120, vacation_used: 24, sick_entitlement: 40, sick_used: 8 },
  { name: "Arin R Ramirez", hire_date: "01/24/2022", birthday: "09/10", vacation_entitlement: 80, vacation_used: 39, sick_entitlement: 40, sick_used: 40 },
  { name: "Bianca M Ramirez", hire_date: "10/28/2021", birthday: "10/08", vacation_entitlement: 80, vacation_used: 80, sick_entitlement: 40, sick_used: 71 },
  { name: "Charles Beard", hire_date: "5/4/2026", birthday: "04/13", vacation_entitlement: 0, vacation_used: 0, sick_entitlement: 0, sick_used: 0 },
  { name: "Charles Dickerson", hire_date: "12/16/2024", birthday: "02/27", vacation_entitlement: 40, vacation_used: 11, sick_entitlement: 40, sick_used: 29 },
  { name: "Chris Brady", hire_date: "07/13/2026", birthday: "09/23", vacation_entitlement: 0, vacation_used: 0, sick_entitlement: 0, sick_used: 0 },
  { name: "Christopher E Miller", hire_date: "09/27/2020", birthday: "06/24", vacation_entitlement: 120, vacation_used: 0, sick_entitlement: 40, sick_used: 0 },
  { name: "Christopher R Marroquin", hire_date: "08/05/2024", birthday: "01/27", vacation_entitlement: 40, vacation_used: 0, sick_entitlement: 40, sick_used: 0 },
  { name: "Eric Gonzalez", hire_date: "01/06/2012", birthday: "09/10", vacation_entitlement: 120, vacation_used: 0, sick_entitlement: 40, sick_used: 0 },
  { name: "Geovany Montes", hire_date: "08/19/2019", birthday: "07/15", vacation_entitlement: 120, vacation_used: 0, sick_entitlement: 40, sick_used: 0 },
  { name: "Humberto Ortiz", hire_date: "08/05/2019", birthday: "01/18", vacation_entitlement: 120, vacation_used: 0, sick_entitlement: 40, sick_used: 7 },
  { name: "Jaden De La Garza", hire_date: "07/07/2025", birthday: "07/15", vacation_entitlement: 40, vacation_used: 0, sick_entitlement: 40, sick_used: 18 },
  { name: "Jared Lurch Esquivel", hire_date: "04/13/2026", birthday: "09/27", vacation_entitlement: 0, vacation_used: 0, sick_entitlement: 0, sick_used: 0 },
  { name: "John J Alvarado", hire_date: "07/22/2019", birthday: "11/07", vacation_entitlement: 120, vacation_used: 0, sick_entitlement: 40, sick_used: 8 },
  { name: "John Williams", hire_date: "10/10/2023", birthday: "05/08", vacation_entitlement: 40, vacation_used: 40, sick_entitlement: 40, sick_used: 40 },
  { name: "Jonathan L Willie", hire_date: "12/20/2021", birthday: "07/26", vacation_entitlement: 80, vacation_used: 80, sick_entitlement: 40, sick_used: 40 },
  { name: "Justin D Lyles", hire_date: "03/03/2021", birthday: "06/23", vacation_entitlement: 120, vacation_used: 0, sick_entitlement: 40, sick_used: 8 },
  { name: "Kai G Woodruff", hire_date: "11/07/2022", birthday: "11/09", vacation_entitlement: 80, vacation_used: 80, sick_entitlement: 40, sick_used: 40 },
  { name: "Kelsie M Gomez", hire_date: "07/09/2019", birthday: "06/10", vacation_entitlement: 120, vacation_used: 0, sick_entitlement: 40, sick_used: 11 },
  { name: "Kenneth Marroquin Jr", hire_date: "09/18/2024", birthday: "01/20", vacation_entitlement: 40, vacation_used: 40, sick_entitlement: 40, sick_used: 40 },
  { name: "Kirk Crumbly", hire_date: "01/10/2025", birthday: "11/24", vacation_entitlement: 40, vacation_used: 40, sick_entitlement: 40, sick_used: 40 },
  { name: "Kyle Duffield", hire_date: "04/01/2025", birthday: "01/14", vacation_entitlement: 40, vacation_used: 25, sick_entitlement: 40, sick_used: 8 },
  { name: "Marcus T Tovar", hire_date: "01/02/2024", birthday: "01/28", vacation_entitlement: 40, vacation_used: 12, sick_entitlement: 40, sick_used: 40 },
  { name: "Michael Casarez", hire_date: "09/05/2023", birthday: "05/31", vacation_entitlement: 40, vacation_used: 40, sick_entitlement: 40, sick_used: 44 },
  { name: "Nathaniel Torres", hire_date: "04/07/2025", birthday: "01/13", vacation_entitlement: 40, vacation_used: 47, sick_entitlement: 40, sick_used: 40 },
  { name: "Noah Maxwell", hire_date: "06/23/2025", birthday: "06/14", vacation_entitlement: 40, vacation_used: 0, sick_entitlement: 40, sick_used: 7 },
  { name: "Omar J Camacho", hire_date: "04/08/2019", birthday: "10/31", vacation_entitlement: 120, vacation_used: 0, sick_entitlement: 40, sick_used: 0 },
  { name: "Roberto F Gonzalez", hire_date: "05/16/2022", birthday: "09/16", vacation_entitlement: 80, vacation_used: 16, sick_entitlement: 40, sick_used: 18 },
  { name: "Warren T Engle", hire_date: "02/01/2020", birthday: "10/09", vacation_entitlement: 120, vacation_used: 30, sick_entitlement: 40, sick_used: 40 },
  { name: "Wayne McCaskill", hire_date: "03/18/2024", birthday: "03/29", vacation_entitlement: 40, vacation_used: 0, sick_entitlement: 40, sick_used: 32 },
  { name: "Will Haire", hire_date: "04/06/2026", birthday: "02/24", vacation_entitlement: 0, vacation_used: 0, sick_entitlement: 0, sick_used: 0 },
];

export type PtoLogImportRow = {
  date_used: string;
  name: string;
  vacation_used?: number;
  sick_used?: number;
  approved_by?: string;
  notes?: string;
};

/** Time Off Log tab from the same PTO Tracker sheet (ledger history — does not change balances). */
export const PTO_SHEET_LOG: PtoLogImportRow[] = [
  { date_used: "10/15/2025", name: "John J Alvarado", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "Migration to new list" },
  { date_used: "10/15/2025", name: "Adam M Bosquez", vacation_used: 40, sick_used: 13, approved_by: "Chris Marroquin", notes: "Migration to new list" },
  { date_used: "10/15/2025", name: "Omar J Camacho", vacation_used: 120, sick_used: 48, approved_by: "Chris Marroquin", notes: "Migration to new list" },
  { date_used: "10/15/2025", name: "Kelsie M Gomez", vacation_used: 16, sick_used: 38, approved_by: "Chris Marroquin", notes: "Migration to new list" },
  { date_used: "10/15/2025", name: "Geovany Montes", vacation_used: 32, sick_used: 5, approved_by: "Chris Marroquin", notes: "Migration to new list" },
  { date_used: "10/15/2025", name: "Humberto Ortiz", vacation_used: 8, sick_used: 8, approved_by: "Chris Marroquin", notes: "Migration to new list" },
  { date_used: "10/15/2025", name: "Bianca M Ramirez", vacation_used: 80, sick_used: 40, approved_by: "Chris Marroquin", notes: "Migration to new list" },
  { date_used: "10/15/2025", name: "Warren T Engle", vacation_used: 64, sick_used: 20, approved_by: "Chris Marroquin", notes: "Migration to new list" },
  { date_used: "10/15/2025", name: "Justin D Lyles", vacation_used: 80, sick_used: 40, approved_by: "Chris Marroquin", notes: "Migration to new list" },
  { date_used: "10/15/2025", name: "Jonathan L Willie", vacation_used: 62, sick_used: 40, approved_by: "Chris Marroquin", notes: "Migration to new list" },
  { date_used: "10/15/2025", name: "Michael Casarez", vacation_used: 0, sick_used: 10, approved_by: "Chris Marroquin", notes: "Migration to new list" },
  { date_used: "10/15/2025", name: "Jaden De La Garza", vacation_used: 40, sick_used: 40, approved_by: "Chris Marroquin", notes: "Migration to new list" },
  { date_used: "10/15/2025", name: "Roberto F Gonzalez", vacation_used: 48, sick_used: 24, approved_by: "Chris Marroquin", notes: "Migration to new list" },
  { date_used: "10/15/2025", name: "Arin R Ramirez", vacation_used: 2, sick_used: 40, approved_by: "Chris Marroquin", notes: "Migration to new list" },
  { date_used: "10/15/2025", name: "Marcus T Tovar", vacation_used: 16, sick_used: 30, approved_by: "Chris Marroquin", notes: "Migration to new list" },
  { date_used: "10/15/2025", name: "Kai G Woodruff", vacation_used: 40, sick_used: 48, approved_by: "Chris Marroquin", notes: "Migration to new list" },
  { date_used: "10/15/2025", name: "Abelardo Herrera", vacation_used: 0, sick_used: 31, approved_by: "Chris Marroquin", notes: "Migration to new list" },
  { date_used: "10/15/2025", name: "Wayne McCaskill", vacation_used: 0, sick_used: 37, approved_by: "Chris Marroquin", notes: "Migration to new list" },
  { date_used: "10/17/2025", name: "Kenneth Marroquin Jr", vacation_used: 0, sick_used: 6, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "10/17/2025", name: "Abelardo Herrera", vacation_used: 0, sick_used: 7, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "10/17/2025", name: "John J Alvarado", vacation_used: 0, sick_used: 2, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "10/17/2025", name: "John Williams", vacation_used: 0, sick_used: 10, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "10/17/2025", name: "Jonathan L Willie", vacation_used: 0, sick_used: 3, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "10/17/2025", name: "Michael Casarez", vacation_used: 0, sick_used: 16, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "10/21/2025", name: "Arin R Ramirez", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "10/21/2025", name: "Roberto F Gonzalez", vacation_used: 0, sick_used: 7, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "10/24/2025", name: "Geovany Montes", vacation_used: 10, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "10/24/2021", name: "Humberto Ortiz", vacation_used: 8, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "10/24/2025", name: "Jonathan L Willie", vacation_used: 6, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "10/24/2025", name: "Kenneth Marroquin Jr", vacation_used: 0, sick_used: 23, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "10/24/2025", name: "Marcus T Tovar", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "10/24/2025", name: "Michael Casarez", vacation_used: 0, sick_used: 2, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "10/24/2025", name: "Roberto F Gonzalez", vacation_used: 0, sick_used: 7, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "10/28/2025", name: "Bianca M Ramirez", vacation_used: 80, sick_used: 40, approved_by: "Chris Marroquin", notes: "Reimbursement for Maternity Leave" },
  { date_used: "10/28/2025", name: "John J Alvarado", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "10/28/2025", name: "Warren T Engle", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "10/28/2025", name: "Kenneth Marroquin Jr", vacation_used: 0, sick_used: 5, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "10/28/2025", name: "Adam M Bosquez", vacation_used: 0, sick_used: 5, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "10/28/2025", name: "Abelardo Herrera", vacation_used: 8, sick_used: 2, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/3/2025", name: "Jonathan L Willie", vacation_used: 8, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/3/2025", name: "Arin R Ramirez", vacation_used: 20, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/3/2025", name: "Adam M Bosquez", vacation_used: 6, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/03/25", name: "Wayne McCaskill", vacation_used: 6, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/03/2025", name: "Marcus T Tovar", vacation_used: 6, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/05/25", name: "John J Alvarado", vacation_used: 0, sick_used: 1, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/10/2025", name: "Kai G Woodruff", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/10/2025", name: "Humberto Ortiz", vacation_used: 8, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/10/2025", name: "Marcus T Tovar", vacation_used: 18, sick_used: 2, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/10/2025", name: "John J Alvarado", vacation_used: 3, sick_used: 21, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/10/2025", name: "Roberto F Gonzalez", vacation_used: 12, sick_used: 2, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/10/2025", name: "Warren T Engle", vacation_used: 0, sick_used: 6, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/10/2025", name: "John Williams", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/10/2025", name: "Jonathan L Willie", vacation_used: 4, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/10/2025", name: "Wayne McCaskill", vacation_used: 4, sick_used: 3, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/10/2025", name: "Kenneth Marroquin Jr", vacation_used: 0, sick_used: 6, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/10/2025", name: "Adam M Bosquez", vacation_used: 16, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/11/2025", name: "Warren T Engle", vacation_used: 0, sick_used: 2, approved_by: "Chris Marroquin", notes: "underpaid 2hrs so Eric gave him cash" },
  { date_used: "11/17/2025", name: "Arin R Ramirez", vacation_used: 11, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/17/2025", name: "Roberto F Gonzalez", vacation_used: 3, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/17/2025", name: "Humberto Ortiz", vacation_used: 7, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/17/2025", name: "John J Alvarado", vacation_used: 2, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/17/2025", name: "Michael Casarez", vacation_used: 0, sick_used: 12, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/17/2025", name: "Warren T Engle", vacation_used: 2, sick_used: 4, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/17/2025", name: "John Williams", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/18/2025", name: "Adam M Bosquez", vacation_used: 0, sick_used: 3, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/24/25", name: "Abelardo Herrera", vacation_used: 8, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/24/2025", name: "Geovany Montes", vacation_used: 0, sick_used: 4, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/24/2025", name: "Kenneth Marroquin Jr", vacation_used: 8, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/24/2025", name: "Roberto F Gonzalez", vacation_used: 1, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "11/24/2025", name: "Warren T Engle", vacation_used: 3, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/01/25", name: "John J Alvarado", vacation_used: 5, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/01/2025", name: "Michael Casarez", vacation_used: 8, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/01/2025", name: "Roberto F Gonzalez", vacation_used: 16, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/01/2025", name: "Kelsie M Gomez", vacation_used: 10, sick_used: 2, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/01/2025", name: "Geovany Montes", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/01/2025", name: "Wayne McCaskill", vacation_used: 8, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/01/2025", name: "Humberto Ortiz", vacation_used: 0, sick_used: 11, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/01/2025", name: "Arin R Ramirez", vacation_used: 12, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/01/2025", name: "Warren T Engle", vacation_used: 15, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/04/2025", name: "Abelardo Herrera", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/09/2025", name: "Humberto Ortiz", vacation_used: 0, sick_used: 2, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/09/2025", name: "Geovany Montes", vacation_used: 0, sick_used: 7, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/09/2025", name: "John Williams", vacation_used: 0, sick_used: 3, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/16/2025", name: "Michael Casarez", vacation_used: 5, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/16/2025", name: "Warren T Engle", vacation_used: 3, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/16/2025", name: "Kelsie M Gomez", vacation_used: 16, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/16/2025", name: "Humberto Ortiz", vacation_used: 6, sick_used: 19, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/16/2025", name: "Arin R Ramirez", vacation_used: 2, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/16/2025", name: "John Williams", vacation_used: 0, sick_used: 5, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/16/2025", name: "Wayne McCaskill", vacation_used: 16, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/12/2025", name: "Warren T Engle", vacation_used: 12, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/15/2025", name: "Kai G Woodruff", vacation_used: 8, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/16/2025", name: "Kai G Woodruff", vacation_used: 8, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/22/2025", name: "Arin R Ramirez", vacation_used: 1, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/22/2025", name: "Jonathan L Willie", vacation_used: 0, sick_used: 32, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/22/2025", name: "Geovany Montes", vacation_used: 0, sick_used: 6, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/29/2025", name: "Jonathan L Willie", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/29/2025", name: "John J Alvarado", vacation_used: 7, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/29/2025", name: "Michael Casarez", vacation_used: 24, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/29/2025", name: "Kenneth Marroquin Jr", vacation_used: 9, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/29/2025", name: "Geovany Montes", vacation_used: 8, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/29/2025", name: "Humberto Ortiz", vacation_used: 17, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/29/2025", name: "Charles Dickerson", vacation_used: 11, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/29/2025", name: "Warren T Engle", vacation_used: 10, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/29/2025", name: "Arin R Ramirez", vacation_used: 8, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "12/29/2025", name: "Wayne McCaskill", vacation_used: 6, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/06/26", name: "Charles Dickerson", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/06/26", name: "Warren T Engle", vacation_used: 10, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/06/26", name: "Abelardo Herrera", vacation_used: 8, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/06/26", name: "Geovany Montes", vacation_used: 32, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/06/26", name: "Humberto Ortiz", vacation_used: 12, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/06/26", name: "Arin R Ramirez", vacation_used: 4, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/06/26", name: "John Williams", vacation_used: 0, sick_used: 6, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/13/26", name: "Michael Casarez", vacation_used: 3, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/13/26", name: "Warren T Engle", vacation_used: 1, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/13/26", name: "Geovany Montes", vacation_used: 8, sick_used: 5, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/13/26", name: "Humberto Ortiz", vacation_used: 7, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/13/26", name: "Arin R Ramirez", vacation_used: 0, sick_used: 7, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/13/26", name: "John Williams", vacation_used: 8, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/13/26", name: "Kai G Woodruff", vacation_used: 0, sick_used: 4, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/13/26", name: "Marcus T Tovar", vacation_used: 0, sick_used: 2, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/20/26", name: "Adam M Bosquez", vacation_used: 8, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/20/26", name: "Kenneth Marroquin Jr", vacation_used: 7, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/20/26", name: "Geovany Montes", vacation_used: 0, sick_used: 4, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/20/26", name: "Humberto Ortiz", vacation_used: 13, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/20/26", name: "John J Alvarado", vacation_used: 6, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/20/26", name: "Jonathan L Willie", vacation_used: 3, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/20/26", name: "Marcus T Tovar", vacation_used: 0, sick_used: 3, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/26/26", name: "John J Alvarado", vacation_used: 32, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/26/26", name: "Kirk Crumbly", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/26/26", name: "Humberto Ortiz", vacation_used: 3, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/26/26", name: "Arin R Ramirez", vacation_used: 20, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "1/26/26", name: "Geovany Montes", vacation_used: 4, sick_used: 1, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/26/26", name: "Marcus T Tovar", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/16/26", name: "John Williams", vacation_used: 19, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "01/16/26", name: "Jonathan L Willie", vacation_used: 27, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/04/26", name: "John J Alvarado", vacation_used: 6, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/04/2026", name: "Michael Casarez", vacation_used: 0, sick_used: 4, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/04/26", name: "Warren T Engle", vacation_used: 0, sick_used: 5, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/04/26", name: "Kelsie M Gomez", vacation_used: 16, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/04/26", name: "Geovany Montes", vacation_used: 16, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/04/26", name: "Humberto Ortiz", vacation_used: 29, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/04/26", name: "Marcus T Tovar", vacation_used: 0, sick_used: 6, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/04/26", name: "Arin R Ramirez", vacation_used: 0, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/04/26", name: "Adam M Bosquez", vacation_used: 16, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/04/26", name: "John Williams", vacation_used: 13, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/09/26", name: "Kirk Crumbly", vacation_used: 0, sick_used: 1, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/09/26", name: "John J Alvarado", vacation_used: 16, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/09/26", name: "Warren T Engle", vacation_used: 0, sick_used: 11, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/09/26", name: "Kelsie M Gomez", vacation_used: 5, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/09/26", name: "Kenneth Marroquin Jr", vacation_used: 3, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/09/26", name: "Geovany Montes", vacation_used: 10, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/09/26", name: "Adam M Bosquez", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/09/26", name: "Jonathan L Willie", vacation_used: 18, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/09/26", name: "Kai G Woodruff", vacation_used: 0, sick_used: 28, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/09/26", name: "Humberto Ortiz", vacation_used: 10, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/16/26", name: "Kelsie M Gomez", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/16/26", name: "Kenneth Marroquin Jr", vacation_used: 7, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/16/26", name: "Marcus T Tovar", vacation_used: 0, sick_used: 11, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/16/26", name: "Jonathan L Willie", vacation_used: 32, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/16/26", name: "John J Alvarado", vacation_used: 14, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/16/26", name: "Kai G Woodruff", vacation_used: 26, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/16/26", name: "Warren T Engle", vacation_used: 0, sick_used: 3, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/23/26", name: "John J Alvarado", vacation_used: 4, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/23/26", name: "Kirk Crumbly", vacation_used: 8, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/23/26", name: "Warren T Engle", vacation_used: 0, sick_used: 1, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "02/24/26", name: "Charles Dickerson", vacation_used: 0, sick_used: 1, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "03/02/26", name: "Charles Dickerson", vacation_used: 0, sick_used: 2, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "03/04/26", name: "John J Alvarado", vacation_used: 0, sick_used: 4, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "03/04/26", name: "Kirk Crumbly", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "03/16/26", name: "Arin R Ramirez", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "03/16/26", name: "Charles Dickerson", vacation_used: 0, sick_used: 4, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "03/16/26", name: "John J Alvarado", vacation_used: 8, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "03/20/26", name: "Kai G Woodruff", vacation_used: 13, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "03/20/26", name: "John J Alvarado", vacation_used: 6, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "03/20", name: "Kelsie M Gomez", vacation_used: 9, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "03/20/26", name: "Marcus T Tovar", vacation_used: 2, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "03/20/26", name: "Warren T Engle", vacation_used: 0, sick_used: 14, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "03/23/26", name: "Kenneth Marroquin Jr", vacation_used: 6, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "03/23/26", name: "Kai G Woodruff", vacation_used: 12, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "03/23/26", name: "Marcus T Tovar", vacation_used: 0, sick_used: 10, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "04/03/26", name: "Arin R Ramirez", vacation_used: 0, sick_used: 6, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "04/03/26", name: "Kai G Woodruff", vacation_used: 5, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "04/03/26", name: "Wayne McCaskill", vacation_used: 0, sick_used: 16, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "04/10/26", name: "John J Alvarado", vacation_used: 6, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "04/10/26", name: "Warren T Engle", vacation_used: 10, sick_used: 6, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "04/10/26", name: "Kelsie M Gomez", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "04/10/26", name: "Wayne McCaskill", vacation_used: 0, sick_used: 16, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "04/10/26", name: "Arin R Ramirez", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "04/10/26", name: "Kai G Woodruff", vacation_used: 8, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "04/10/26", name: "Nathaniel Torres", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "04/17/26", name: "Warren T Engle", vacation_used: 5, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "04/17/26", name: "Kyle Duffield", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "04/17/26", name: "Kirk Crumbly", vacation_used: 0, sick_used: 9, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "04/24/26", name: "Kelsie M Gomez", vacation_used: 6, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "05/08/26", name: "Justin D Lyles", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "05/08/26", name: "Nathaniel Torres", vacation_used: 0, sick_used: 16, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "05/15/26", name: "Arin R Ramirez", vacation_used: 0, sick_used: 2, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "05/23.26", name: "Wayne McCaskill", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "05/23/26", name: "Nathaniel Torres", vacation_used: 0, sick_used: 16, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "05/23/26", name: "Marcus T Tovar", vacation_used: 8, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "05/23/26", name: "Kelsie M Gomez", vacation_used: 2, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "05/26/26", name: "Warren T Engle", vacation_used: 7, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "05/26/26", name: "Charles Dickerson", vacation_used: 0, sick_used: 4, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "05/26/26", name: "Arin R Ramirez", vacation_used: 0, sick_used: 9, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "06/05/26", name: "Arin R Ramirez", vacation_used: 0, sick_used: 3, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "06/05/26", name: "Charles Dickerson", vacation_used: 0, sick_used: 4, approved_by: "Chris Marroquin", notes: "Chris" },
  { date_used: "06/05/2026", name: "Bianca M Ramirez", vacation_used: 0, sick_used: 31, approved_by: "Chris Marroquin", notes: "Bianca Sick Pay Advancement" },
  { date_used: "06/12/26", name: "Arin R Ramirez", vacation_used: 3, sick_used: 4, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "06/12/26", name: "Charles Dickerson", vacation_used: 0, sick_used: 6, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "06/12/26", name: "Kelsie M Gomez", vacation_used: 6, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "06/12/26", name: "Kirk Crumbly", vacation_used: 32, sick_used: 14, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "06/19/25", name: "Nathaniel Torres", vacation_used: 25, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "06/27/26", name: "Arin R Ramirez", vacation_used: 7, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "06/27/26", name: "John J Alvarado", vacation_used: 5, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "06/27/26", name: "Nathaniel Torres", vacation_used: 22, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "06/25/26", name: "Roberto F Gonzalez", vacation_used: 16, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "07/14/26", name: "Abelardo Herrera", vacation_used: 16, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "07/24/26", name: "Jaden De La Garza", vacation_used: 0, sick_used: 6, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "07/24/26", name: "Kelsie M Gomez", vacation_used: 0, sick_used: 11, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "07/24/26", name: "Roberto F Gonzalez", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "07/31/26", name: "Jaden De La Garza", vacation_used: 0, sick_used: 12, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "07/31/26", name: "Kyle Duffield", vacation_used: 25, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "07/31/26", name: "Marcus T Tovar", vacation_used: 2, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "07/31/26", name: "Arin R Ramirez", vacation_used: 9, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "07/31/26", name: "Roberto F Gonzalez", vacation_used: 0, sick_used: 2, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "08/07/26", name: "Warren T Engle", vacation_used: 8, sick_used: 0, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "08/07/26", name: "Noah Maxwell", vacation_used: 0, sick_used: 2, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "08/14/26", name: "John J Alvarado", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "08/14/26", name: "Noah Maxwell", vacation_used: 0, sick_used: 5, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "08/14/26", name: "Roberto F Gonzalez", vacation_used: 0, sick_used: 8, approved_by: "Chris Marroquin", notes: "per employee request" },
  { date_used: "08/21/26", name: "Humberto Ortiz", vacation_used: 0, sick_used: 7, approved_by: "Chris Marroquin", notes: "per employee request" },
];
